name: Rust CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Build civkit-cli
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --package civkit-cli --verbose

    - name: Build civkitd
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --package civkitd --verbose

    - name: Build civkit-sample
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --package civkit-sample --verbose

  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: Build civkit-cli
      run: cargo build --package civkit-cli --verbose

    - name: Build civkitd
      run: cargo build --package civkitd --verbose

    - name: Build civkit-sample
      run: cargo build --package civkit-sample --verbose
