name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        rust:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Setup environment
      run: |
        export LC_ALL=C.UTF-8
        echo "Environment setup completed."
    - name: Build and check civkit-cli
      run: |
        ./ci/ubuntu/build_civkit-cli.sh
        if [ -f "civkit-cli" ]; then
            echo "civkit-cli build: SUCCESS"
        else
            echo "civkit-cli build: FAILURE"
            exit 1
        fi
    - name: Build and check civkitd
      run: |
        ./ci/ubuntu/build_civkitd.sh
        if [ -f "civkitd" ]; then
            echo "civkitd build: SUCCESS"
        else
            echo "civkitd build: FAILURE"
            exit 1
        fi
    - name: Build and check civkit-sample
      run: |
        ./ci/ubuntu/build_civkit-sample.sh
        if [ -f "civkit-sample" ]; then
            echo "civkit-sample build: SUCCESS"
        else
            echo "civkit-sample build: FAILURE"
            exit 1
        fi
