name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Build civkit-cli
        run: |
          cd ci/ubuntu
          ./setup_env.sh
          ./build_civkit-cli.sh

      - name: Build civkitd
        run: |
          cd ci/ubuntu
          ./setup_env.sh
          ./build_civkitd.sh

      - name: Build civkit-sample
        run: |
          cd ci/ubuntu
          ./setup_env.sh
          ./build_civkit-sample.sh
