name: Rust CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust:
          - stable
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Install protobuf compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Build civkit-cli
      run: cargo build --bin civkit-cli --verbose

    - name: Build civkitd
      run: cargo build --bin civkitd --verbose

    - name: Build civkit-sample
      run: cargo build --bin civkit-sample --verbose

  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl build-essential protobuf-compiler
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env

    - name: Build civkit-cli
      run: cargo build --bin civkit-cli --verbose

    - name: Build civkitd
      run: cargo build --bin civkitd --verbose

    - name: Build civkit-sample
      run: cargo build --bin civkit-sample --verbose
