name: Rust CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, debian-latest]
        rust:
          - stable
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2

    - name: Install Rust Toolchain (stable)
      run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
    
    - name: Install protobuf compiler
      run: |
        if [ "${{ matrix.os }}" == "macos-13" ]; then
          brew install protobuf
        else
          sudo apt-get install -y protobuf-compiler
        fi

    - name: Build civkit-cli
      run: cargo build --bin civkit-cli --verbose

    - name: Build civkitd
      run: cargo build --bin civkitd --verbose

    - name: Build civkit-sample
      run: cargo build --bin civkit-sample --verbose
